### ISSUE TITLE
Issues with newicks found in the wild

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsconvert#13]
Trying to load a newick file as output by the nextstrain pipeline results in:
`dendropy.utility.error.UltrametricityError: Tree is not ultrametric within threshold of 1e-05`

The `dendropy` import checks for ultrametricity can be disabled by calling `tree.calc_node_ages(ultrametricity_precision=-1)` just before you iterator over the tree. However as dendropy's node-time calculations rely on this and you then end up with parents that are erroneously younger than children, which tskit is obviously not happy about.

An alternative to work out the node times is to:
```python
    tree.calc_node_root_distances()
    max_d = max(node.root_distance for node in tree)
    for node in tree:
        node.age = max_d - node.root_distance
```

This works, as long as there are no zero-length branches, which need to be set to `epsilon` to be tskit compatible.

It seems it would be good to incorporate these tweaks to make the newick import more compatible.

**Comment by jeromekelleher** [comment]
Branch lengths are a miserable mess in newick, and in general I think you can't assume they mean much. I've seen trees where the branch lengths are the number of mutations on the branch, which have no correspondance to time.

I think we'll just have to add options for how branch lengths are interpreted, like ``branch_length="time"|"mutations"|...`` or something.

But yes, I guess assuming the trees are ultrametric is very restrictive and we should compute the node times ourselves.
