### ISSUE TITLE
Newick + csv/tsv import

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsconvert#14]
It is a very common workflow in phylogenetics to have a newick file and a csv/tsv with metadata about the nodes in the tree. It should be possible to import both, or one then the other to automatically create a tree sequence with appropriate metadata and schemas.

**Comment by jeromekelleher** [comment]
Great idea!

**Comment by benjeffery** [comment]
I've started work on this, but hit https://github.com/tskit-dev/tsconvert/issues/13 and will fix first.
