### ISSUE TITLE
Negative branch lengths

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tsconvert#38]
Phylogenetic inference programs can sometimes produce negative branch lengths. To deal with this, I would set negative branch lengths to zero in the `ape` R package before doing any analysis. Maybe we should allow for reading in negative branch lengths when using the `from_` methods? Also, maybe we can add an argument to allow users to set negative branch lengths to zero?

**Comment by szhan** [comment]
Ah, oops, I didn't notice this argument `min_edge_length`, but it doesn't allow branch lengths of zero.

**Comment by benjeffery** [comment]
You can't have negative lengths in a valid tree sequence, so not sure it would be much use?

**Comment by jeromekelleher** [comment]
Can't have zero branch lengths @szhan, as it violates a basic tree sequence requirement. In practise we'd fiddle in some small epsilon.
