### ISSUE TITLE
from_newick does not import node names

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsconvert#47]
The docstring for `from_newick` says "Newick names and comments will be written to the node metadata", but that appears not to be the case:

```
>>> ts = tsconvert.from_newick("(n1:1,n2:1);")
>>> ts.node(0)  # No metadata
Node(id=0, flags=0, time=1.0, population=-1, individual=-1, metadata={})
```

**Comment by benjeffery** [comment]
There's code to do this (https://github.com/tskit-dev/tsconvert/blob/main/tsconvert/newick.py#L176) and tests (https://github.com/tskit-dev/tsconvert/blob/main/tests/test_newick.py#L479) so not sure what is happening here.

**Comment by hyanwong** [comment]
My bad. Node 0 here is the root,. The metadata is in nodes 1 & 2
