### ISSUE TITLE
from_ms doesn't like full ms output

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsconvert#5]
The `from_ms()` function expects only the newick trees from ms, whereas these lines are usually followed in the ms output by a line such as `segsites: 1045`. That means when I pipe an input string straight from the ms output into `from_ms` I get an error like

```
ValueError: Line not in ms format: missing [
```

Should we say somewhere that you need to parse the ms output so that only the trees lines are passed to our function, or should we e.g. detect the initial word `segsites` and stop tree reading without error if so. My preference is the latter, FWIW.

**Comment by jeromekelleher** [comment]
This is a bug all right. Ultimately we'll want to read in the haplotypes and use them to place mutations on the tree (see https://github.com/tskit-dev/tskit/issues/99), but for now just finishing tree reading when we see "segsites" is good. PR welcome!

**Comment by hyanwong** [comment]
Why don't we just read all the trees in one go using 

`trees = dendropy.TreeList.get(ContiguousLinesStartingWithSquareBrace)`

Then we don't need to faff around with all that parsing ourselves. The position of the tree (i.e. the number in square brackets) will be in tree[0].comments[0], tree[1].comments[0], etc.

**Comment by jeromekelleher** [comment]
Sure, if that works. I don't know the library well --- if someone else has done this then great.

**Comment by hyanwong** [comment]
OK, will modify my existing PR, since it's all the same issue really.

**Comment by jeromekelleher** [comment]
This was fixed in #7.
